### ISSUE TITLE
The app doesn't run well after the Java rewrite

### ISSUE THREAD

**Issue by carmocca** [scholzj/milestone-check#27]
We were using this app in https://github.com/PyTorchLightning/pytorch-lightning and it was working flawlessly.

Around February, we started noticing that the job wasn't running or updating on some PRs. Coincidentally this was just after this commit: https://github.com/scholzj/milestone-check/commit/bf07889d550f8c7a29394dc7bb327c35b1280665

Is there any way we can use the previous version? Have you noticed these issues yourself? Since it's an app, we don't have access to any logs but it should be easy to reproduce.

We had to remove the required check from the CI for this reason.

Thank you for your help.

**Comment by scholzj** [comment]
I can have a look at the logs. But I haven't noticed any issues on my projects. Any examples of issues where you had problems?

**Comment by carmocca** [comment]
For example, this PR which I just opened https://github.com/PyTorchLightning/pytorch-lightning/pull/12672

![image](https://user-images.githubusercontent.com/11067892/162477239-c0e976a5-462d-4f9f-9c49-ce24cab49c76.png)

**Comment by scholzj** [comment]
It looks like it fails to decode the JSON of your PR. It seems to have problem with the `auto-merge` section. I will have a look to see what is the issue over the weekend.

**Comment by akihironitta** [comment]
cc @Borda

**Comment by scholzj** [comment]
Ok, I fixed the issue, it looks like the native build of the Java app did not include the AutoMerge class properly. So when you enabled Auto Merge on your PRs, it failed to handle it. The new version is now deployed, so please give it a try and let me know if you see some more issues. Thanks.
