### ISSUE TITLE
Transform into a GitHub action

### ISSUE THREAD

**Issue by steebchen** [scholzj/milestone-check#7]
It would be awesome if this could be turned into a GitHub action, so there's no need setup a bot/to ask your organisation for bot access – you can just add a GitHub Action.

**Comment by scholzj** [comment]
I will have a look - TBH I have not much idea how exactly the GitHub actions work.

**Comment by scholzj** [comment]
I gave this a try - https://github.com/scholzj/milestone-check-action ... but it does not work so well as GitHub app does:
* GitHub App is easier to get working even with PRs from forks, which is where GitHUb Actions seemed to be not so straight forward (the default token doesn't allow me to set additional PR status Checks on PR from fork without providing custom GitHub token)
* The Milestone Check workflow needs to be triggered both for pull_request as well as issues events (issues events are triggered for milestone changes while `pull_request_ are triggered for push events. This causes chaos with regards to the set status. I found out the best was to use separate status for Milestone Check versus for the GitHub action run to be able to reconcile between the two different event triggers.

I these things are not an issue for you, feel free to use it. I will probably stay with the app for the places where I use it.

**Comment by steebchen** [comment]
Thanks for working on this! The limitations are quite unfortunate, but I guess better than no action at all. Is my understanding right that the need for both `pull_request` and `issues` are more a limitation of Github Actions than the milestone check bot? i.e. I'd expect that `pull_request` would also get triggered for a milestone change?

**Comment by scholzj** [comment]
> Is my understanding right that the need for both pull_request and issues are more a limitation of Github Actions than the milestone check bot? i.e. I'd expect that pull_request would also get triggered for a milestone change?

This is more issue with the event model wich GitHub has, when some changes to the PR are fired as issue events and some are as a pull request events. And for the milestone, you need to check both:
* You need to update the status after each push into the PR, because that would otherwise wipe the status
* You need to watch the issue events because that is what is fired when the milestone is changed.

The GitHub App is watching both as well.

**Comment by steebchen** [comment]
Thanks for the clarification. Not ideal but good enough for my use-cases, so thanks a lot again for publishing this action!
