### ISSUE TITLE
Make the status "pending" rather than "failed".

### ISSUE THREAD

**Issue by iphydf** [scholzj/milestone-check#8]
"Failed" status indicates that something is broken and I don't really need to look at a PR yet. Milestone is something I put once the PR is in a good state.

If this is not something you'd like to change globally, make it configurable in the org/.github repo.

**Comment by scholzj** [comment]
I think you are right. I would make sense to leave it as pending. I will change it when I find some time.

**Comment by scholzj** [comment]
@iphydf This change should now be live.

**Comment by iphydf** [comment]
Confirmed. Thanks!
