### ISSUE TITLE
App is unreliable (sometimes)

### ISSUE THREAD

**Issue by janpio** [scholzj/milestone-check#9]
Take this PR as an example: https://github.com/prisma/prisma-examples/pull/1776 - It definitely has a milestone attached but the app still shows pending. This is a problem as the success of the checks would trigger an automated merge of the PR.

Could it be the the app somehow is not triggered reliably or does not report back? Any way to work around this for us?

(With many other PRs like https://github.com/prisma/prisma-examples/pull/1782 it works just fine of course and does an awesome job.)

**Comment by scholzj** [comment]
I haven't seen this in the projects where I'm using it. But in the logs there were some reports about it running out of memory when too many reuqests came at the same time. So I doubled the memory and hope it helps.

**Comment by janpio** [comment]
Awesome. By removing and readding the milestone I could indeed fix all the PRs I was aware of that were stuck, so this might have solved the problem <3

**Comment by jrfnl** [comment]
Just ran into this as well and removing & re-adding the milestone did fix it.
